name: C/C++ CI

on:
  push:
    branches:
      - v6_web_develop
  pull_request:
    branches:
      - v6_web_develop

jobs:
  Web:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.20
          actions-cache-folder: 'emsdk'

      - name: Install Boost
        uses: ./.github/actions/download-boost
        with:
          version: '1.74.0'
          cache-name: cache-boost-headers
          destination: Dependencies/boost_1_74_0

      - name: Prebuild Third-party Libraries
        run: |
          embuilder.py build ogg vorbis

      - name: Configure Siv3D
        working-directory: Web
        run: |
          mkdir build && cd build
          emcmake cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build Siv3D
        working-directory: Web
        run: |
          cmake --build build --parallel 4

      - name: Run Siv3DTest
        working-directory: Web/build
        run: |
          export DISPLAY=:1
          Xvfb -ac ${DISPLAY} -screen 0 1280x1024x24 > /dev/null 2>&1 &
          emrun --browser chrome --timeout 600 --timeout_returncode -1 Siv3DTest.html
          emrun --browser chrome --timeout 600 --timeout_returncode -1 Siv3DUnitTest.html

      - name: Install Siv3D
        working-directory: Web
        run: |
          cmake --install build

      - name: Configure Siv3DApp
        working-directory: Web/App
        run: |
          mkdir build && cd build
          emcmake cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build Siv3DApp
        working-directory: Web/App
        run: |
          cmake --build build

      - name: Run Siv3DApp
        working-directory: Web/App
        run: |
          export DISPLAY=:1
          cd build
          emrun --browser chrome --timeout 180 --timeout_returncode 0 Siv3DApp.html
